# Gunakan base image nginx
FROM nginx

# Install git untuk clone repository
RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

# Clone repository dari GitHub
RUN git clone https://github.com/abilmhsn/UAS-CC.git /tmp/repo

# Salin isi folder html ke direktori nginx
RUN cp -r /tmp/repo/project-docker-html/* /usr/share/nginx/html/

# Expose port (nginx default is 80)
EXPOSE 80
